#baseURL = "https://livestoriz.onrender.com"
baseURL = ""
languageCode = "en-us"
title = "Livestoriz | Art of Living"
theme = "ananke"

#from anake example

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Personal blog on solid programming principles and API design."
  facebook = "https://www.facebook.com/Livestoriz"
  twitter = "https://twitter.com/livestoriz"
  instagram = "https://www.instagram.com/kovacs.alex1"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  #featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  featured_image = "https://live.staticflickr.com/5633/23808147225_aaf61385a5_z.jpg"
  recent_posts_number = 10
